# Generated by Django 4.2.11 on 2025-03-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work_name', models.CharField(unique=True, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Тип научной работы',
                'verbose_name_plural': 'Типы научных работ',
                'db_table': 'TypesOfWorks',
            },
        ),
        migrations.CreateModel(
            name='IntelForScienceWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('annotation', models.TextField(null=True, unique=True, verbose_name='Аннотация')),
                ('authors', models.CharField(max_length=150, null=True, verbose_name='Авторы')),
                ('OECD', models.CharField(max_length=150, verbose_name='OECD')),
                ('key_words', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ключевые слова')),
                ('year_publication', models.IntegerField(verbose_name='Год публикации')),
                ('journal_name', models.CharField(max_length=150, verbose_name='Название издательства')),
                ('type_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.typesofwork', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Информация о научной работе',
                'verbose_name_plural': 'Информация о научных работах',
                'db_table': 'ScienceData',
            },
        ),
    ]
