# Generated by Django 4.2.11 on 2025-04-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authornames',
            name='author_last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='authornames',
            name='author_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='authornames',
            name='author_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
