# Generated by Django 4.2.11 on 2025-03-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typesofwork',
            old_name='type_of_work_name',
            new_name='name',
        ),
    ]
