# Generated by Django 4.2.11 on 2025-03-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_type_of_work_name_typesofwork_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intelforscienceworks',
            old_name='title',
            new_name='name',
        ),
    ]
