# Generated by Django 4.2.11 on 2025-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_authornames_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='key_words',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключевые слова'),
        ),
    ]
