# Generated by Django 4.2.11 on 2025-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_title_intelforscienceworks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='annotation',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='authors',
            field=models.CharField(max_length=200, null=True, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='journal_name',
            field=models.CharField(max_length=230, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='key_words',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
