# Generated by Django 4.2.11 on 2025-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authornames',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Имена всех авторов'},
        ),
    ]
