# Generated by Django 4.2.11 on 2025-03-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_intelforscienceworks_annotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='OECD',
            field=models.CharField(max_length=250, verbose_name='OECD'),
        ),
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='authors',
            field=models.CharField(max_length=250, null=True, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='journal_name',
            field=models.CharField(max_length=300, verbose_name='Название издательства'),
        ),
    ]
