# Generated by Django 4.2.11 on 2025-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_intelforscienceworks_oecd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelforscienceworks',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
    ]
